# Generated by Django 4.2.20 on 2025-04-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_stripe_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
