# Generated by Django 4.2.20 on 2025-04-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palace', '0004_alter_product_available_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('time_event', models.DateTimeField(verbose_name='Время мероприятия')),
                ('slug', models.CharField(max_length=200, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
                'ordering': ['time_event'],
                'indexes': [models.Index(fields=['id', 'slug'], name='palace_shed_id_0476a3_idx'), models.Index(fields=['name'], name='palace_shed_name_9602d0_idx'), models.Index(fields=['-time_event'], name='palace_shed_time_ev_0a8003_idx')],
            },
        ),
    ]
